spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/shared
        git:
          uri: https://github.com/ArtemBeltiukov/microservices-config.git
          default-label: main
  profiles:
    active: git

server:
  port: ${CONFIG_PORT:8888}