version: '3'
networks:
  local:
    driver: bridge
  docker-elk_elk:
    external: true
  
services:
  workplaces3:
    mem_limit: 256mb
    build:
      context: D:\epam\projects\master\docker\dockerfiles\workplaces3\
      
    container_name: workplaces3
    image: workplaces3:latest
    
    volumes:
      - "./web/src:/web/src"
    ports:
      - "9095:9095"
    
    depends_on:
      - eureka
    restart:
      on-failure:10
    
    networks:
      - local
      - docker-elk_elk

  workplaces2:
    mem_limit: 256mb
    build:
      context: D:\epam\projects\master\docker\dockerfiles\workplaces2\
      
    container_name: workplaces2
    image: workplaces2:latest
    
    volumes:
      - "./web/src:/web/src"
    ports:
      - "9091:9091"
    
    depends_on:
      - eureka
    restart:
      on-failure:10
    
    networks:
      - local
      - docker-elk_elk

  workplaces1:
    mem_limit: 256mb
    build:
      context: D:\epam\projects\master\docker\dockerfiles\workplaces1\
      
    container_name: workplaces1
    image: workplaces1:latest
    
    volumes:
      - "./web/src:/web/src"
    ports:
      - "9090:9090"
    
    depends_on:
      - eureka
    restart:
      on-failure:10
    
    networks:
      - local
      - docker-elk_elk
      
  gateway:
    mem_limit: 256mb
    build:
      context: D:\epam\projects\master\docker\dockerfiles\gateway\
      
    container_name: gateway
    image: gateway:latest
    
    volumes:
      - "./web/src:/web/src"
    ports:
      - "9094:9094"
    
    depends_on:
      - eureka
    restart:
      on-failure:10
    
    networks:
      - local  
      - docker-elk_elk
      
  employees:
    mem_limit: 256mb
    build:
      context: D:\epam\projects\master\docker\dockerfiles\employees\
      
    container_name: employees
    image: employees:latest
    
    volumes:
      - "./web/src:/web/src"
    ports:
      - "9092:9092"
    depends_on:
      - eureka
    restart:
      on-failure:10
    networks:
      - local 
      - docker-elk_elk      
      
  eureka:
    build:
      context: D:\epam\projects\master\docker\dockerfiles\eureka\
      
    container_name: eureka
    image: eureka:latest
    
    volumes:
      - "./web/src:/web/src"
    ports:
      - "8282:8282"
      
    depends_on:
      - config
    restart:
      on-failure:10
    
    networks:
      - local 
      - docker-elk_elk

  
  config:
    mem_limit: 256mb
    build:
      context: D:\epam\projects\master\docker\dockerfiles\config\
      
    container_name: config
    image: config:latest
    
    volumes:
      - "./web/src:/web/src"
    ports:
      - "8888:8888"
    
    networks:
      - local
      - docker-elk_elk
      
